16330456Otomasyon/Controllers/AnasayfaController.cs
using _16330456Otomasyon.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _16330456Otomasyon.Controllers
{
    
    public class AnasayfaController : Controller
    {
        private kutuphaneEntities db = new kutuphaneEntities();
        // GET: Anasayfa
        public ActionResult Index()
        {
            if (Session["KullaniciId"] == null) {
                return RedirectToAction("Index", "GirisYap");
            }
            else {
                
                return View(db.Kitaps.ToList());
            }
        }
    }
}

16330456Otomasyon/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _16330456Otomasyon.Models;

namespace _16330456Otomasyon.Controllers
{
    public class KategoriController : Controller
    {
        private kutuphaneEntities db = new kutuphaneEntities();

        // GET: Kategori
        public ActionResult Index()
        {
            if (Session["KullaniciId"] == null)
            {
                return RedirectToAction("Index", "GirisYap");
            }
            else
            {
                return View(db.Kategoris.ToList());
            }
        }

        // GET: Kategori/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["KullaniciId"] == null)
            {
                return RedirectToAction("Index", "GirisYap");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Kategori kategori = db.Kategoris.Find(id);
                if (kategori == null)
                {
                    return HttpNotFound();
                }
                return View(kategori);
            }
        }

        // GET: Kategori/Create
        public ActionResult Create()
        {
            if (Session["KullaniciId"] == null)
            {
                return RedirectToAction("Index", "GirisYap");
            }
            else
            {
                return View();
            }
        }

        // POST: Kategori/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Kategori1")] Kategori kategori)
        {
            if (Session["KullaniciId"] == null)
            {
                return RedirectToAction("Index", "GirisYap");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    db.Kategoris.Add(kategori);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(kategori);
            }
        }

        // GET: Kategori/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["KullaniciId"] == null)
            {
                return RedirectToAction("Index", "GirisYap");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Kategori kategori = db.Kategoris.Find(id);
                if (kategori == null)
                {
                    return HttpNotFound();
                }
                return View(kategori);
            }
        }

        // POST: Kategori/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Kategori1")] Kategori kategori)
        {
            if (Session["KullaniciId"] == null)
            {
                return RedirectToAction("Index", "GirisYap");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    db.Entry(kategori).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(kategori);
            }
        }

        // GET: Kategori/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["KullaniciId"] == null)
            {
                return RedirectToAction("Index", "GirisYap");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Kategori kategori = db.Kategoris.Find(id);
                if (kategori == null)
                {
                    return HttpNotFound();
                }
                return View(kategori);
            }
        }

        // POST: Kategori/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["KullaniciId"] == null)
            {
                return RedirectToAction("Index", "GirisYap");
            }
            else
            {
                Kategori kategori = db.Kategoris.Find(id);
                db.Kategoris.Remove(kategori);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

16330456Otomasyon/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _16330456Otomasyon.Models;
using System.IO;

namespace _16330456Otomasyon.Controllers
{
    public class KitapController : Controller
    {
        private kutuphaneEntities db = new kutuphaneEntities();

        // GET: Kitap
        public ActionResult Index()
        {
            if (Session["KullaniciId"] == null)
            {
                return RedirectToAction("Index", "GirisYap");
            }
            else
            {
                var kitaps = db.Kitaps.Include(k => k.Kategori).Include(k => k.Kullanici);
                return View(kitaps.ToList());
            }
        }

        // GET: Kitap/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["KullaniciId"] == null)
            {
                return RedirectToAction("Index", "GirisYap");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Kitap kitap = db.Kitaps.Find(id);
                if (kitap == null)
                {
                    return HttpNotFound();
                }
                return View(kitap);
            }
        }

        // GET: Kitap/Create
        public ActionResult Create()
        {
            if (Session["KullaniciId"] == null)
            {
                return RedirectToAction("Index", "GirisYap");
            }
            else
            {
                ViewBag.KategoriId = new SelectList(db.Kategoris, "Id", "Kategori1");
                ViewBag.EkleyenKullaniciId = new SelectList(db.Kullanicis, "Id", "KullaniciAdi");
                return View();
            }
        }

        // POST: Kitap/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,KitapAdi,KitapYazar,KitapISBN,KategoriId,Aciklama,YayinTarihi,EklenmeTarihi,KitapAdert,EkleyenKullaniciId,Resim")] Kitap kitap, DosyaModel dosya)
        {
            if (Session["KullaniciId"] == null)
            {
                return RedirectToAction("Index", "GirisYap");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    string serverYol = Server.MapPath("~/Content/Resimler");//server yeri
                    string dosyaAdi = Path.GetFileName(dosya.Resim.FileName);//dosya adı
                    dosya.Resim.SaveAs(Path.Combine(serverYol, dosyaAdi));//birleştirerek kaydetmek
                    kitap.Resim = dosyaAdi;
                    db.Kitaps.Add(kitap);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.KategoriId = new SelectList(db.Kategoris, "Id", "Kategori1", kitap.KategoriId);
            ViewBag.EkleyenKullaniciId = new SelectList(db.Kullanicis, "Id", "KullaniciAdi", kitap.EkleyenKullaniciId);
            return View(kitap);
        }

        // GET: Kitap/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["KullaniciId"] == null)
            {
                return RedirectToAction("Index", "GirisYap");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Kitap kitap = db.Kitaps.Find(id);
                if (kitap == null)
                {
                    return HttpNotFound();
                }
                ViewBag.KategoriId = new SelectList(db.Kategoris, "Id", "Kategori1", kitap.KategoriId);
                ViewBag.EkleyenKullaniciId = new SelectList(db.Kullanicis, "Id", "KullaniciAdi", kitap.EkleyenKullaniciId);
                return View(kitap);
            }
        }

        // POST: Kitap/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,KitapAdi,KitapYazar,KitapISBN,KategoriId,Aciklama,YayinTarihi,EklenmeTarihi,KitapAdert,EkleyenKullaniciId,Resim")] Kitap kitap, DosyaModel dosya)
        {
            if (Session["KullaniciId"] == null)
            {
                return RedirectToAction("Index", "GirisYap");
            }
            else
            {
                
                if (ModelState.IsValid)
                {
                    /*string serverYol = Server.MapPath("~/Content/Resimler");//server yeri
                    string dosyaAdi = Path.GetFileName(dosya.Resim.FileName);//dosya adı
                    dosya.Resim.SaveAs(Path.Combine(serverYol, dosyaAdi));//birleştirerek kaydetmek
                    kitap.Resim = dosyaAdi;*/

                    db.Entry(kitap).State = EntityState.Modified;
                    db.SaveChanges();
                   
                    return RedirectToAction("Index");
                }
                ViewBag.KategoriId = new SelectList(db.Kategoris, "Id", "Kategori1", kitap.KategoriId);
                ViewBag.EkleyenKullaniciId = new SelectList(db.Kullanicis, "Id", "KullaniciAdi", kitap.EkleyenKullaniciId);

                

                return View(kitap);

            }
        }

        // GET: Kitap/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["KullaniciId"] == null)
            {
                return RedirectToAction("Index", "GirisYap");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Kitap kitap = db.Kitaps.Find(id);
                if (kitap == null)
                {
                    return HttpNotFound();
                }
                return View(kitap);
            }
        }

        // POST: Kitap/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["KullaniciId"] == null)
            {
                return RedirectToAction("Index", "GirisYap");
            }
            else
            {
                Kitap kitap = db.Kitaps.Find(id);
                db.Kitaps.Remove(kitap);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

16330456Otomasyon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title </title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/dist/css/skins/_all-skins.min.css">
    <!-- Morris chart -->
    <link rel="stylesheet" href="~/plugins/morris/morris.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="~/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="~/plugins/datepicker/datepicker3.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="~/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <!--
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    -->
</head> 
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index", "Anasayfa")" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>K</b>O</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Kütüphane</b>Otomasyon</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">


                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="hidden-xs">@Session["KullaniciAdi"]</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header" style="height:100px;">
                                    
                                    <p>
                                        @Session["KullaniciAdi"]

                                    </p>
                                    <div class="pull-right">
    <a href="@Url.Action("CikisYap", "GirisYap")" class="btn btn-default btn-flat">Çıkış Yap</a>
</div>
                                </li>
                               
                 
                            </ul>
                        </li>
                        
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header">Menu</li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-book"></i> <span>Kitaplar</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li class=""><a href="@Url.Action("Index", "Kitap")"><i class="fa fa-circle-o"></i>Tüm Kitaplar</a></li>
                            <li><a href="@Url.Action("Create", "Kitap")"><i class="fa fa-plus"></i>Yeni Kitap Ekle</a></li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-th-list" aria-hidden="true"></i> <span>Kategoriler</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li class=""><a href="@Url.Action("Index", "Kategori")"><i class="fa fa-circle-o"></i>Tüm Katagoriler</a></li>
                            <li><a href="@Url.Action("Create", "Kategori")"><i class="fa fa-plus"></i>Yeni Kategori Ekle</a></li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-user" aria-hidden="true"></i> <span>Kullanıcılar</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li class=""><a href="@Url.Action("Index", "Kullanici")"><i class="fa fa-circle-o"></i>Tüm Kullanıcılar</a></li>
                            <li><a href="@Url.Action("Create", "Kullanici")"><i class="fa fa-plus"></i>Yeni Kullanıcı Ekle</a></li>
                        </ul>
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper" style="background-color:#eee;">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @ViewBag.title
                </h1>
            </section>
            <!-- Main content -->
            <section class="content" style="margin:50px 50px 0 50px ; background-color:#fff">
                @RenderBody()
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>16330456</b>
            </div>
            <strong>&copy; @DateTime.Now.Year - Nuh Mehmet Demirkol - 16330456 - Kütüphane Otomasyonu
        </footer>

        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3.1.1 -->
    <script src="~/plugins/jQuery/jquery-3.1.1.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
  $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/bootstrap/js/bootstrap.min.js"></script>
    <!-- Morris.js charts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="~/plugins/morris/morris.min.js"></script>
    <!-- Sparkline -->
    <script src="~/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="~/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/plugins/knob/jquery.knob.js"></script>
    <!-- daterangepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- datepicker -->
    <script src="~/plugins/datepicker/bootstrap-datepicker.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="~/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <!-- Slimscroll -->
    <script src="~/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/plugins/fastclick/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/dist/js/demo.js"></script>

    <!--
    <body>

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                </div>
            </div>
        </div>

        <div class="container body-content">
            
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>

    </body>-->
</html>

16330456Otomasyon/Views/Shared/_login.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Kütüphaneye Giriş </title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/dist/css/skins/_all-skins.min.css">
    <!-- Morris chart -->
    <link rel="stylesheet" href="~/plugins/morris/morris.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="~/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="~/plugins/datepicker/datepicker3.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="~/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">


</head> 
<body style="background:url(../../Content/Resimler/loginbg.jpg);background-position:center bottom;background-size:100%;">
    <div class="login-box ">
        <div class="login-logo">
            <a href=""><b>Kütüphane</b>OTOMASYONU</a>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg">Kütüphane otomasyonuna giriş yapınız</p>
            <p class="login-box-msg">Kullanıcı Adı : Görevli</p>
            <p class="login-box-msg">Şifre : 123456</p>
            @RenderBody()

        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->

    <!-- jQuery 3.1.1 -->
    <script src="~/plugins/jQuery/jquery-3.1.1.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
  $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/bootstrap/js/bootstrap.min.js"></script>
    <!-- Morris.js charts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="~/plugins/morris/morris.min.js"></script>
    <!-- Sparkline -->
    <script src="~/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="~/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/plugins/knob/jquery.knob.js"></script>
    <!-- daterangepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- datepicker -->
    <script src="~/plugins/datepicker/bootstrap-datepicker.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="~/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <!-- Slimscroll -->
    <script src="~/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/plugins/fastclick/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/dist/js/demo.js"></script>

    <!--
    <body>

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                </div>
            </div>
        </div>

        <div class="container body-content">
            
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>

    </body>-->
</html>